[2023-09-04T06:03:10.586+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2021-12-22T00:00:00+00:00 [queued]>
[2023-09-04T06:03:10.601+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2021-12-22T00:00:00+00:00 [queued]>
[2023-09-04T06:03:10.602+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-04T06:03:10.698+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2021-12-22 00:00:00+00:00
[2023-09-04T06:03:10.708+0000] {standard_task_runner.py:57} INFO - Started process 5725 to run task
[2023-09-04T06:03:10.713+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2021-12-22T00:00:00+00:00', '--job-id', '607', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpey1mpwih']
[2023-09-04T06:03:10.716+0000] {standard_task_runner.py:85} INFO - Job 607: Subtask insert_into_table
[2023-09-04T06:03:10.794+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2021-12-22T00:00:00+00:00 [running]> on host 10bdc2e98230
[2023-09-04T06:03:10.908+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2021-12-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-12-22T00:00:00+00:00'
[2023-09-04T06:03:10.910+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2021-12-22', 'dag_with_postgres_operator_v04')
        
[2023-09-04T06:03:10.922+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T06:03:10.932+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T06:03:10.947+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2021-12-22', 'dag_with_postgres_operator_v04')
        , parameters: None
[2023-09-04T06:03:10.951+0000] {sql.py:427} INFO - Rows affected: 1
[2023-09-04T06:03:10.969+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, execution_date=20211222T000000, start_date=20230904T060310, end_date=20230904T060310
[2023-09-04T06:03:11.005+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-04T06:03:11.036+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-04T06:04:00.178+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2021-12-22T00:00:00+00:00 [queued]>
[2023-09-04T06:04:00.219+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2021-12-22T00:00:00+00:00 [queued]>
[2023-09-04T06:04:00.219+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-04T06:04:00.422+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2021-12-22 00:00:00+00:00
[2023-09-04T06:04:00.436+0000] {standard_task_runner.py:57} INFO - Started process 5989 to run task
[2023-09-04T06:04:00.448+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2021-12-22T00:00:00+00:00', '--job-id', '702', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpsp_rn4ie']
[2023-09-04T06:04:00.454+0000] {standard_task_runner.py:85} INFO - Job 702: Subtask insert_into_table
[2023-09-04T06:04:00.628+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2021-12-22T00:00:00+00:00 [running]> on host 10bdc2e98230
[2023-09-04T06:04:00.889+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohghaff' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2021-12-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-12-22T00:00:00+00:00'
[2023-09-04T06:04:00.892+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2021-12-22', 'dag_with_postgres_operator_v04')
        
[2023-09-04T06:04:00.919+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T06:04:00.963+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T06:04:00.999+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2021-12-22', 'dag_with_postgres_operator_v04')
        , parameters: None
[2023-09-04T06:04:01.018+0000] {sql.py:427} INFO - Rows affected: 1
[2023-09-04T06:04:01.054+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, execution_date=20211222T000000, start_date=20230904T060400, end_date=20230904T060401
[2023-09-04T06:04:01.152+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-04T06:04:01.196+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
