[2023-09-04T06:07:19.883+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2023-09-04T06:07:19.897+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2023-09-04T06:07:19.897+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-04T06:07:19.918+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2022-08-29 00:00:00+00:00
[2023-09-04T06:07:19.927+0000] {standard_task_runner.py:57} INFO - Started process 7686 to run task
[2023-09-04T06:07:19.931+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2022-08-29T00:00:00+00:00', '--job-id', '1434', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp8lcxc0jb']
[2023-09-04T06:07:19.934+0000] {standard_task_runner.py:85} INFO - Job 1434: Subtask insert_into_table
[2023-09-04T06:07:20.050+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-08-29T00:00:00+00:00 [running]> on host 10bdc2e98230
[2023-09-04T06:07:20.224+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohghaff' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2022-08-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-29T00:00:00+00:00'
[2023-09-04T06:07:20.226+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2022-08-29', 'dag_with_postgres_operator_v04')
        
[2023-09-04T06:07:20.237+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T06:07:20.248+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T06:07:20.265+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2022-08-29', 'dag_with_postgres_operator_v04')
        , parameters: None
[2023-09-04T06:07:20.271+0000] {sql.py:427} INFO - Rows affected: 1
[2023-09-04T06:07:20.292+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, execution_date=20220829T000000, start_date=20230904T060719, end_date=20230904T060720
[2023-09-04T06:07:20.344+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-04T06:07:20.371+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
