[2023-09-04T06:02:15.487+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-03-11T00:00:00+00:00 [queued]>
[2023-09-04T06:02:15.499+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-03-11T00:00:00+00:00 [queued]>
[2023-09-04T06:02:15.500+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-04T06:02:15.517+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2022-03-11 00:00:00+00:00
[2023-09-04T06:02:15.525+0000] {standard_task_runner.py:57} INFO - Started process 5222 to run task
[2023-09-04T06:02:15.530+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2022-03-11T00:00:00+00:00', '--job-id', '396', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp0fp5uwdy']
[2023-09-04T06:02:15.532+0000] {standard_task_runner.py:85} INFO - Job 396: Subtask insert_into_table
[2023-09-04T06:02:15.595+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-03-11T00:00:00+00:00 [running]> on host 10bdc2e98230
[2023-09-04T06:02:15.709+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2022-03-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-03-11T00:00:00+00:00'
[2023-09-04T06:02:15.711+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2022-03-11', 'dag_with_postgres_operator_v04')
        
[2023-09-04T06:02:15.724+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T06:02:15.733+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T06:02:15.747+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2022-03-11', 'dag_with_postgres_operator_v04')
        , parameters: None
[2023-09-04T06:02:15.751+0000] {sql.py:427} INFO - Rows affected: 1
[2023-09-04T06:02:15.767+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, execution_date=20220311T000000, start_date=20230904T060215, end_date=20230904T060215
[2023-09-04T06:02:15.822+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-04T06:02:15.841+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-04T06:05:00.337+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-03-11T00:00:00+00:00 [queued]>
[2023-09-04T06:05:00.366+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-03-11T00:00:00+00:00 [queued]>
[2023-09-04T06:05:00.367+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-04T06:05:00.414+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2022-03-11 00:00:00+00:00
[2023-09-04T06:05:00.427+0000] {standard_task_runner.py:57} INFO - Started process 6540 to run task
[2023-09-04T06:05:00.433+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2022-03-11T00:00:00+00:00', '--job-id', '941', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpca76cyaq']
[2023-09-04T06:05:00.437+0000] {standard_task_runner.py:85} INFO - Job 941: Subtask insert_into_table
[2023-09-04T06:05:00.649+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-03-11T00:00:00+00:00 [running]> on host 10bdc2e98230
[2023-09-04T06:05:00.974+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohghaff' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2022-03-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-03-11T00:00:00+00:00'
[2023-09-04T06:05:00.979+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2022-03-11', 'dag_with_postgres_operator_v04')
        
[2023-09-04T06:05:01.011+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T06:05:01.039+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T06:05:01.092+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2022-03-11', 'dag_with_postgres_operator_v04')
        , parameters: None
[2023-09-04T06:05:01.108+0000] {sql.py:427} INFO - Rows affected: 1
[2023-09-04T06:05:01.158+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, execution_date=20220311T000000, start_date=20230904T060500, end_date=20230904T060501
[2023-09-04T06:05:01.217+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-04T06:05:01.269+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
