[2023-09-04T06:08:02.803+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-10-27T00:00:00+00:00 [queued]>
[2023-09-04T06:08:02.833+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-10-27T00:00:00+00:00 [queued]>
[2023-09-04T06:08:02.833+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-04T06:08:02.863+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2022-10-27 00:00:00+00:00
[2023-09-04T06:08:02.923+0000] {standard_task_runner.py:57} INFO - Started process 8131 to run task
[2023-09-04T06:08:02.928+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2022-10-27T00:00:00+00:00', '--job-id', '1629', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpx3n51ocp']
[2023-09-04T06:08:02.933+0000] {standard_task_runner.py:85} INFO - Job 1629: Subtask insert_into_table
[2023-09-04T06:08:03.115+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-10-27T00:00:00+00:00 [running]> on host 10bdc2e98230
[2023-09-04T06:08:03.371+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohghaff' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2022-10-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-10-27T00:00:00+00:00'
[2023-09-04T06:08:03.376+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2022-10-27', 'dag_with_postgres_operator_v04')
        
[2023-09-04T06:08:03.400+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T06:08:03.420+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T06:08:03.439+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2022-10-27', 'dag_with_postgres_operator_v04')
        , parameters: None
[2023-09-04T06:08:03.448+0000] {sql.py:427} INFO - Rows affected: 1
[2023-09-04T06:08:03.474+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, execution_date=20221027T000000, start_date=20230904T060802, end_date=20230904T060803
[2023-09-04T06:08:03.545+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-04T06:08:03.570+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
