[2023-09-04T06:02:03.117+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-02-24T00:00:00+00:00 [queued]>
[2023-09-04T06:02:03.140+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-02-24T00:00:00+00:00 [queued]>
[2023-09-04T06:02:03.141+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-04T06:02:03.175+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2022-02-24 00:00:00+00:00
[2023-09-04T06:02:03.185+0000] {standard_task_runner.py:57} INFO - Started process 5116 to run task
[2023-09-04T06:02:03.191+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2022-02-24T00:00:00+00:00', '--job-id', '342', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpz1aaevbe']
[2023-09-04T06:02:03.194+0000] {standard_task_runner.py:85} INFO - Job 342: Subtask insert_into_table
[2023-09-04T06:02:03.276+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-02-24T00:00:00+00:00 [running]> on host 10bdc2e98230
[2023-09-04T06:02:03.431+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2022-02-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-02-24T00:00:00+00:00'
[2023-09-04T06:02:03.434+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2022-02-24', 'dag_with_postgres_operator_v04')
        
[2023-09-04T06:02:03.451+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T06:02:03.466+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T06:02:03.487+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2022-02-24', 'dag_with_postgres_operator_v04')
        , parameters: None
[2023-09-04T06:02:03.493+0000] {sql.py:427} INFO - Rows affected: 1
[2023-09-04T06:02:03.516+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, execution_date=20220224T000000, start_date=20230904T060203, end_date=20230904T060203
[2023-09-04T06:02:03.563+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-04T06:02:03.795+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-04T06:04:47.323+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-02-24T00:00:00+00:00 [queued]>
[2023-09-04T06:04:47.365+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-02-24T00:00:00+00:00 [queued]>
[2023-09-04T06:04:47.366+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-04T06:04:47.436+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2022-02-24 00:00:00+00:00
[2023-09-04T06:04:47.454+0000] {standard_task_runner.py:57} INFO - Started process 6417 to run task
[2023-09-04T06:04:47.466+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2022-02-24T00:00:00+00:00', '--job-id', '895', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp5n57cmho']
[2023-09-04T06:04:47.474+0000] {standard_task_runner.py:85} INFO - Job 895: Subtask insert_into_table
[2023-09-04T06:04:47.642+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-02-24T00:00:00+00:00 [running]> on host 10bdc2e98230
[2023-09-04T06:04:48.008+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohghaff' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2022-02-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-02-24T00:00:00+00:00'
[2023-09-04T06:04:48.012+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2022-02-24', 'dag_with_postgres_operator_v04')
        
[2023-09-04T06:04:48.048+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T06:04:48.085+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T06:04:48.119+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2022-02-24', 'dag_with_postgres_operator_v04')
        , parameters: None
[2023-09-04T06:04:48.129+0000] {sql.py:427} INFO - Rows affected: 1
[2023-09-04T06:04:48.159+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, execution_date=20220224T000000, start_date=20230904T060447, end_date=20230904T060448
[2023-09-04T06:04:48.240+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-04T06:04:48.275+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
