[2023-09-04T06:02:34.266+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-04-03T00:00:00+00:00 [queued]>
[2023-09-04T06:02:34.277+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-04-03T00:00:00+00:00 [queued]>
[2023-09-04T06:02:34.278+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-04T06:02:34.297+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2022-04-03 00:00:00+00:00
[2023-09-04T06:02:34.305+0000] {standard_task_runner.py:57} INFO - Started process 5385 to run task
[2023-09-04T06:02:34.308+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2022-04-03T00:00:00+00:00', '--job-id', '460', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpd_m6i3qh']
[2023-09-04T06:02:34.311+0000] {standard_task_runner.py:85} INFO - Job 460: Subtask insert_into_table
[2023-09-04T06:02:34.379+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-04-03T00:00:00+00:00 [running]> on host 10bdc2e98230
[2023-09-04T06:02:34.494+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2022-04-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-04-03T00:00:00+00:00'
[2023-09-04T06:02:34.496+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2022-04-03', 'dag_with_postgres_operator_v04')
        
[2023-09-04T06:02:34.505+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T06:02:34.514+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T06:02:34.529+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2022-04-03', 'dag_with_postgres_operator_v04')
        , parameters: None
[2023-09-04T06:02:34.534+0000] {sql.py:427} INFO - Rows affected: 1
[2023-09-04T06:02:34.550+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, execution_date=20220403T000000, start_date=20230904T060234, end_date=20230904T060234
[2023-09-04T06:02:34.602+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-04T06:02:34.619+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-04T06:05:16.907+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-04-03T00:00:00+00:00 [queued]>
[2023-09-04T06:05:16.924+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-04-03T00:00:00+00:00 [queued]>
[2023-09-04T06:05:16.924+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-04T06:05:16.952+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2022-04-03 00:00:00+00:00
[2023-09-04T06:05:16.962+0000] {standard_task_runner.py:57} INFO - Started process 6667 to run task
[2023-09-04T06:05:16.965+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2022-04-03T00:00:00+00:00', '--job-id', '1002', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp5216ot1w']
[2023-09-04T06:05:16.968+0000] {standard_task_runner.py:85} INFO - Job 1002: Subtask insert_into_table
[2023-09-04T06:05:17.050+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2022-04-03T00:00:00+00:00 [running]> on host 10bdc2e98230
[2023-09-04T06:05:17.214+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohghaff' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2022-04-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-04-03T00:00:00+00:00'
[2023-09-04T06:05:17.216+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2022-04-03', 'dag_with_postgres_operator_v04')
        
[2023-09-04T06:05:17.235+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T06:05:17.251+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T06:05:17.271+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2022-04-03', 'dag_with_postgres_operator_v04')
        , parameters: None
[2023-09-04T06:05:17.277+0000] {sql.py:427} INFO - Rows affected: 1
[2023-09-04T06:05:17.299+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, execution_date=20220403T000000, start_date=20230904T060516, end_date=20230904T060517
[2023-09-04T06:05:17.339+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-04T06:05:17.438+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
